### ISSUE TITLE
Caught exception: Error: listen EADDRINUSE :::8000

### ISSUE THREAD

**Issue by thomastao0215** [dvajs/dva-hackernews#9]
jiachen215 (master #) dva-hackernews-master $ sudo npm start
Password:

> @ start /Users/jiachen215/Desktop/dva-hackernews-master
> dora --plugins "proxy,webpack,webpack-hmr"

(node:8821) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
Caught exception: Error: listen EADDRINUSE :::8000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at /Users/jiachen215/Desktop/dva-hackernews-master/node_modules/.0.3.3@dora/lib/index.js:93:12
    at /Users/jiachen215/Desktop/dva-hackernews-master/node_modules/.1.5.2@async/lib/async.js:718:13
    at Immediate.iterate (/Users/jiachen215/Desktop/dva-hackernews-master/node_modules/.1.5.2@async/lib/async.js:262:13)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
AnyProxy is about to exit with code: 0

**Comment by sorrycc** [comment]
> Caught exception: Error: listen EADDRINUSE :::8000

8000 端口被占了。

**Comment by thomastao0215** [comment]
谢谢云谦老师
